Require rake ~> 10.5.0 when running tests
Fixes exception: `NoMethodError: undefined method 'last_comment' for #<Rake::Application:...>`.

Sorts development dependencies in gemspec.

Use normal release of capybara gem instead of fetching from GitHub.