Fix typo in changelog
Change upgrade notice to specify the right method

When adding `use_application_hashing` in `config/doorkeeper.rb` file I get an exception `NoMethodError: undefined method `use_application_hashing' for #<Doorkeeper::Config::Builder`.
It turns out that the right setting is `hash_application_secrets` instead.