Handle trying authorization with client credentials
When trying to start a new authorization for an application with grant
flow 'client_credentials' (which also has redirect_uri nil), the
following error occurs:

NoMethodError: undefined method `split' for nil:NilClass

lib/doorkeeper/oauth/helpers/uri_checker.rb:66 valid_for_authorization?
lib/doorkeeper/oauth/pre_authorization.rb:89 validate_redirect_uri
lib/doorkeeper/validations.rb:13 block in validate
lib/doorkeeper/validations.rb:12 each
lib/doorkeeper/validations.rb:12 validate
lib/doorkeeper/validations.rb:19 valid?
lib/doorkeeper/oauth/pre_authorization.rb:32 authorizable?
app/controllers/doorkeeper/authorizations_controller.rb:8 new

Moving the validation for supporting grant flows up, prevents this
error from happening (and shows an error message to the user, instead of
a 500 Internal Server Error).